### ISSUE TITLE
Home assistant 0.99.1 in Docker log fool of error "KeyError: 'switch"

### ISSUE THREAD

**Issue by hellad** [peterbuga/HASS-sonoff-ewelink#149]
Hi @peterbuga 

Can you help to solve the issue with a lot of error messages in my Home assistant 0.99.1 system installed on Synology DS 918+ in Docker.
I have LED lamp and couple of 2-gang switches and see in the log almost every minute the following error message :

2019-09-28 23:42:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/sonoff/switch.py", line 48, in is_on
    self._state = self.get_state()
  File "/config/custom_components/sonoff/__init__.py", line 662, in get_state
    return device['params']['switch'] == 'on' if device else False
**KeyError: 'switch'**

In eWelink app everything looks working properly.
I created debug devices.json file in case it would be helpful. [Link](https://cloud.mail.ru/public/3TqB/MmMNg666f)
Thank you for this component!

**Comment by difelice** [comment]
Hi, I believe that was already fixed on `master` earlier today.

**Comment by hellad** [comment]
@difelice 
Unfortunately no, it was not fixed.
I just copied the latest version of code in init and sensor files and receive the same error messages.  
2019-09-29 00:53:33 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/sonoff/switch.py", line 48, in is_on
    self._state = self.get_state()
  File "/config/custom_components/sonoff/__init__.py", line 662, in get_state
    return device['params']['switch'] == 'on' if device else False
KeyError: 'switch'

I'm not able now to switch on/off lights from Homeassistant lovelace GUI. I see error 'Sonoff' object has no attributes 'switch'

**Comment by difelice** [comment]
I see. Try this branch https://github.com/peterbuga/HASS-sonoff-ewelink/issues/143

**Comment by hellad** [comment]
@difelice Thank you for the link!
I didn't know that there is another branch. It seems like working properly now in my environment and I can use LED lamp too. 
**There is now error messages in the log for a while.**

Just for statistical purposes I put the [link to my model of 2-gang switches](https://www.aliexpress.com/item/32961290914.html) on Aliexpress.

**Comment by peterbuga** [comment]
@hellad see this too https://github.com/peterbuga/HASS-sonoff-ewelink/issues/145#issuecomment-536173192
